---
apiVersion: v1
kind: Namespace
metadata:
  name: clb-test-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clb-test-01
  labels:
    app: clb-test-01
#name space change 
  namespace: clb-test-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clb-test-01
  template:
    metadata:
      labels:
        app: clb-test-01
    spec:
      containers:
#     - image: 507115347197.dkr.ecr.ap-northeast-2.amazonaws.com/network-multitool
      - image: "whchoi98/network-multitool"
        imagePullPolicy: Always
        name: "clb-test-01"
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
#add nodeSelector
      nodeSelector:
         nodegroup-type: "managed-frontend-workloads"
---
apiVersion: v1
kind: Service
metadata:
  name: clb-test-01-svc
  namespace: clb-test-01
spec:
  selector:
    app: clb-test-01
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 80

        
