apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-test-01
  labels:
    app: cluster-test-01
#name space change 
  namespace: cluster-test-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-test-01
  template:
    metadata:
      labels:
        app: cluster-test-01
    spec:
      containers:
      - image: whchoi98/network-multitool
        imagePullPolicy: Always
        name: cluster-test-01
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
  #add nodeSelector
      nodeSelector:
        nodegroup-type: "frontend-workloads"      
