---
apiVersion: v1
kind: Namespace
metadata:
  name: nlb-test-03
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlb-test-03
  labels:
    app: nlb-test-03
#name space change 
  namespace: nlb-test-03
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nlb-test-03
  template:
    metadata:
      labels:
        app: nlb-test-03
    spec:
      containers:
      - image: whchoi98/network-multitool
        imagePullPolicy: Always
        name: nlb-test-03
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
#add nodeSelector
      nodeSelector:
        nodegroup-type: "managed-backend-workloads"


        
