apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlb-test-01
  labels:
    app: nlb-test-01
#name space change 
  namespace: nlb-test-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nlb-test-01
  template:
    metadata:
      labels:
        app: nlb-test-01
    spec:
      containers:
#     - image: 507115347197.dkr.ecr.ap-northeast-2.amazonaws.com/network-multitool
      - image: whchoi98/network-multitool
        imagePullPolicy: Always
        name: nlb-test-01
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
#add nodeSelector
      nodeSelector:
        Node-Type: "unmgmd-public"

        
