apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-app-02
  labels:
    app: alpine-app-02
#name space change 
  namespace: network-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-app-02
  template:
    metadata:
      labels:
        app: alpine-app-02
    spec:
      containers:
      - image: 507115347197.dkr.ecr.ap-northeast-2.amazonaws.com/network-multitool
        imagePullPolicy: Always
        name: alpine-app-02
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
#add nodeSelector
      nodeSelector:
        nodegroup-type: "backend-workloads"
