apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-app-02
  labels:
    app: alpine-app-02
#name space change 
  namespace: network-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-app-02
  template:
    metadata:
      labels:
        app: alpine-app-02
    spec:
      containers:
      - image: praqma/network-multitool
        imagePullPolicy: Always
        name: alpine-app-02
        ports:
        - containerPort: 80
          protocol: TCP
#add nodeSelector
      nodeSelector:
        nodegroup-type: "frontend-workloads"
