apiVersion: v1
kind: Service
metadata:
  name: alpine-app
  namespace: network-test
spec:
  selector:
    app: alpine-app
# type: LoadBalancer
  type: Nodeport
  ports:
   -  protocol: TCP
      nodePort: 30080
      port: 8080
      targetPort: 80


