---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
  labels:
    app: supermario
spec:
  replicas: 3
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
      - name: mario
        image: pengbai/docker-supermario
      nodeSelector:
        nodegroup-type: "managed-backend-workloads"
---
apiVersion: v1
kind: Service
metadata:
  name: supermario
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  namespace: supermario
spec:
  externalTrafficPolicy: Local
  selector:
    app: supermario
  ports:
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
EOF

